{% set name = "PyDispatcher" %}
{% set version = "2.0.6" %}
{% set sha256 = "3d7e4f43c70000a1dca31f92694e99d0101934fa6eab5d5455a758858d86df95" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pydispatch

about:
  home: http://pydispatcher.sourceforge.net
  license: BSD 3-Clause
  license_family: BSD
  license_file: license.txt
  summary: Multi-producer-multi-consumer signal dispatching mechanism

  description: |
    Multi-producer-multi-consumer signal dispatching mechanism
  doc_url: http://pydispatcher.sourceforge.net/
  dev_url: http://pydispatcher.sourceforge.net/

extra:
  recipe-maintainers:
    - shyuep
